[Definition]
failregex = ^.*NOTICE.* .*: Registration from '.*' failed for '<HOST>(:[0-9]+)?'.*$
            ^.*NOTICE.* .*: Failed to authenticate device .*@<HOST>.*$
            ^.*SECURITY.*SecurityEvent="FailedACL".*RemoteAddress="IPV[46]/(UDP|TCP|TLS)/<HOST>/.*$
            ^.*SECURITY.*SecurityEvent="InvalidAccountID".*RemoteAddress="IPV[46]/(UDP|TCP|TLS)/<HOST>/.*$
ignoreregex =
