[general]
enabled = yes
port = 5038
bindaddr = 0.0.0.0
displayconnects = no

[pbxami]
secret = ${AMI_PASSWORD}
read = system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan
write = system,call,command,agent,user,config,originate,message
