[modules]
autoload=yes
noload => chan_sip.so
load => res_pjsip.so
load => res_pjsip_transport_websocket.so
load => res_http_websocket.so
load => res_ari.so
load => res_ari_channels.so
load => app_queue.so
load => app_voicemail.so
load => app_confbridge.so
load => app_mixmonitor.so
