[general]
autofill=yes
shared_lastcall=yes

[sales]
strategy=rrmemory
timeout=20
retry=5
wrapuptime=5
maxlen=0
musicclass=default
joinempty=yes
leavewhenempty=no
; Add dynamic members through AMI/API in production.
member => PJSIP/1000,1000
