[general]
format=wav49|gsm|wav
attach=yes
serveremail=pbx@localhost
maxmsg=100
maxsecs=300
minsecs=2
skipms=3000
maxsilence=10
silencethreshold=128

[default]
1000 => 1000,Administrator,admin@example.com
